# General
title: Dump Tecnologia RS
email: oi@dump.tec.br
source: .
destination: ./public
baseurl: ""
url: https://dump.tec.br
srcurl: "/"
lang: pt-BR
locale: pt_BR
author: Dump Tecnologia
google_analytics: "" # UA-111111111-1
published: true
staticforms_api_key:

# Site Paths
post_path: assets/images/posts/
icon_path: assets/icons/
image_path: assets/images/
css_path: assets/css/
js_path: assets/scripts/

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-autoprefixer
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
sass:
  sass_dir: assets/css
  style: compressed
exclude:
  - .github
  - Gemfile
  - Gemfile.lock
  - README.md
  - .gitignore
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - app
  - .idea
  - server.sh
  - LICENSE